{"name": "test_multiplication_11[3-35]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (11 * 3) == 35", "trace": "num = 3, output = 35\n\n    @pytest.mark.parametrize(\"num, output\",[(1,11),(2,22),(3,35),(4,44)])\n    def test_multiplication_11(num, output):\n>      assert 11*num == output\nE      assert (11 * 3) == 35\n\ntest_allure.py:7: AssertionError"}, "parameters": [{"name": "num", "value": "3"}, {"name": "output", "value": "35"}], "start": 1596468077045, "stop": 1596468077045, "uuid": "1728ae36-f010-4c71-ab53-666adbfd0ae1", "historyId": "a8e1f7f9c88d1037b8b0e6b1ca39792c", "testCaseId": "4508990e4f3fc76931bfa23a7a5fe7f7", "fullName": "test_allure#test_multiplication_11", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "DESKTOP-GE3UEJE"}, {"name": "thread", "value": "23824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}